# Use an official Python runtime as a parent image
FROM python:3.11-slim

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy the requirements.txt and install the dependencies
COPY requirements/requirements-train.txt ./
RUN pip install --no-cache-dir -r requirements-train.txt

# Copy the train.py script into the container
COPY scripts/train.py ./

#Copy the .env file into the container
COPY .env ./

# Run train.py when the container starts
CMD ["python", "train.py"]
