# Use an official Python runtime as a parent image
FROM python:3.11-slim

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy the requirements.txt and install the dependencies
COPY requirements/requirements-load.txt ./
RUN pip install --no-cache-dir -r requirements-load.txt

# Copy the load.py script into the container
COPY scripts/load.py ./

#Copy the .env file into the container
COPY .env ./

# Run load.py when the container starts
CMD ["python", "load.py"]
